name: Create releases for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-release:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        poetry-version: [ 1.1.6 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Disable virtualenvs
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Build executable
        run: pyinstaller --clean pyinstaller.spec

      - name: Make executable
        run: chmod +x dist/fakexrandr_background/fakexrandr_background

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fakexrandr_background-${{ matrix.os }}
          path: dist/fakexrandr_background